use BANANA_CINEMA;

INSERT INTO `ROLES`(`role_id`, `mo_ta`) VALUES (1, 'Admin');
INSERT INTO `ROLES`(`role_id`, `mo_ta`) VALUES (2, 'Khach hang');
INSERT INTO `ROLES`(`role_id`, `mo_ta`) VALUES (3, 'Nhan vien');

-- INSERT DEFAULT USER
INSERT INTO `USERS` (`user_name`, `password`, `ho_ten`, `gioi_tinh`, `ngay_sinh`, `sdt`, `dia_chi`, `cmnd`, `active`) VALUES ('admin', '$2y$12$vuUlslGcdoHI0przFYwDh.1I9BgEbm0lWo0BqFV7FyfstQC6/.nia', 'admin', NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO `USERS` (`user_name`, `password`, `ho_ten`, `gioi_tinh`, `ngay_sinh`, `sdt`, `dia_chi`, `cmnd`, `active`) VALUES ('khachhang1', '$2y$12$vuUlslGcdoHI0przFYwDh.1I9BgEbm0lWo0BqFV7FyfstQC6/.nia', N'Khách hàng', NULL, NULL, NULL, NULL, NULL, '1');
INSERT INTO `USERS` (`user_name`, `password`, `ho_ten`, `gioi_tinh`, `ngay_sinh`, `sdt`, `dia_chi`, `cmnd`, `active`) VALUES ('nhanvien1', '$2y$12$vuUlslGcdoHI0przFYwDh.1I9BgEbm0lWo0BqFV7FyfstQC6/.nia', N'Nhân viên', NULL, NULL, NULL, NULL, NULL, '1');

-- INSERT DEFAULT USER_ROLE
INSERT INTO `USER_ROLE` (`user_id`, `role_id`) VALUES ('1', '1');
INSERT INTO `USER_ROLE` (`user_id`, `role_id`) VALUES ('2', '2');
INSERT INTO `USER_ROLE` (`user_id`, `role_id`) VALUES ('3', '3');

-- INSERT PHIM
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'ETERNALS - CHỦNG TỘC BẤT TỬ', N'Marvel Studios', 'Mỹ', N'Angelina Jolie, Salma Hayek, Gemma Chan, Richard Madden, Kit Harington, Ma Dong Seok', N'Chloé Zhao', N'Hành Động', '2021-12-03', N'Vũ trụ điện ảnh Marvel mở ra thần thoại về chủng tộc Eternals – những người bất tử đã sống trên Trái Đất từ thuở sơ khai, hình thành nên các nền văn minh nhân loại. Chỉ đạo Eternals là đạo diễn vừa đoạt Oscar 2021 - Chloé Zhao. Phim quy tụ dàn ngôi sao hạng A Hollywood như Salma Hayek, Angelina Jolie. \r\nTrong trailer đầu tiên, Eternals đã cung cấp cho khán giả những thông tin cơ bản về nguồn gốc cũng như mục đích đến Trái Đất của những siêu anh hùng mới này. Đến trailer thứ hai được tung ra cách đây không lâu, nhà sản xuất mang đến những thước phim giàu cảm xúc hơn rất nhiều cũng như hé lộ chân dung của những kẻ thù, mối nguy hại mà các vị thần phải đối mặt… \r\nCâu hỏi lớn nhất được đặt ra sau khi trailer đầu tiên của Eternals xuất hiện chính là: Sở hữu sức mạnh như vậy nhưng tại sao các vị thần này lại không giải cứu con người trước sự tàn phá của Thanos? \r\nVà câu trả lời đã có trong chính trailer tiếp theo. Cụ thể theo Sersi: “Chúng tôi được dặn không xen vào mâu thuẫn của con người, trừ khi có dính đến Deviant (sinh vật sở hữu kích thước vô cùng khổng lồ nhưng năng lực thì thua các Eternals)”. \r\nVậy thì ai đã quy định với họ như thế? Chắc chắn chúng ta chỉ có thể chờ đến lúc phim chính thức ra rạp mới biết được đáp án chính xác nhất.', '155');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'SHANG-CHI VÀ HUYỀN THOẠI THẬP LUÂN', N'Walt Disney Pictures', N'Mỹ', N'Simu Liu, Lương Triều Vỹ, Awkwafina', N'Destin Daniel Cretton', N'Hành Động', '2021-11-26', N'Bộ phim tiếp theo của vũ trụ điện ảnh Marvel với nhân vật chính là \"Bậc Thầy Kung-Fu\" Shang-Chi. \r\nShang-Chi là bậc thầy Kung Fu, tinh thông võ thuật. Sức mạnh của Shang-Chi đến từ hàng ngàn giờ luyện tập miệt mài và sự kỷ luật cao độ với bản thân. Siêu anh hùng võ thuật này được chính bố của mình tôi luyện, dạy dỗ để trở thành một sát thủ chuyên nghiệp và kế thừa tập đoàn tội ác của ông. \r\nShang-Chi có lẽ không còn xa lạ với người hâm mộ truyện tranh Marvel, tuy nhiên, đây sẽ là lần đầu tiên nhân vật này được bước lên màn ảnh. Đặc biệt hơn, Shang-Chi cũng chính là nhân vật siêu anh hùng gốc Á đầu tiên của MCU được chuyển thể thành phim. \r\nTeaser trailer đầu tiên cũng hé lộ những hình ảnh thời niên thiếu của Shang-Chi, từ một cậu bé nhỏ tuổi được cha mình khổ luyện, đào tạo trong môi trường vô cùng khắc nghiệt cho tới khi trở thành một người đàn ông trưởng thành. Xuyên suốt trailer dài 2 phút là những pha phô diễn võ thuật, công phu choáng ngợp, đậm chất Á Đông, đúng như cội nguồn của nhân vật này. ', '132');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'BLACK WIDOW - GÓA PHỤ ĐEN', N'Marvel Studios', N'Mỹ', N'Scarlett Johansson, Florence Pugh, Rachel Weisz', N'Cate Shortland', N'Hành Động, Giả Tưởng, Phiêu Lưu', '2021-11-19', N'Cùng với cái chết của Iron Man, sự ra đi của Black Widow Natasha Romanoff là mất mát không thể thay thế của team Avengers. Người phụ nữ vừa mạnh mẽ vừa dịu dàng, coi Biệt Đội Siêu Anh Hùng như “gia đình” đã ra đi mãi mãi để đổi lấy viên đá linh hồn. Sự hy sinh của cô để lại trong lòng các fan vũ trụ điện ảnh Marvel niềm đau khó tả. \r\nMay mắn thay, Marvel thấu hiểu tình yêu người hâm mộ dành cho Góa Phụ Đen. Dù khó thể trở lại trong tương lai MCU, Natasha và fan được “tặng” một bộ phim riêng mặc sức tung hoành. Cuộc hành trình độc lập của nữ chiến binh xuất sắc nhất Avengers sẽ đưa cô đụng độ một trong những kẻ thù “sừng sỏ” nhất – chuyên gia copy Taskmaster. \r\nChuyến phiêu lưu sẽ đưa lên màn ảnh rộng quá khứ của Black Widow trước khi gia nhập S.H.I.E.L.D. Natasha sẽ gặp lại “gia đình” cũ gồm các đặc vụ Yelena Belova (Florence Pugh), Melina Vostokoff (Rachel Weisz), Alexei Shostakov hay còn gọi là Red Guardian (David Harbour). \r\nĐặc biệt, theo nhiều tin đồn, “Iron Man” Tony Stark dù đã tạm biệt MCU vẫn xuất hiện trong phim. \r\nSau một năm thành công với hai đề cử Oscar Nữ chính xuất sắc nhất (Marriage Story) và Nữ phụ xuất sắc nhất (Jojo Rabbit), Black Widow chắc chắn sẽ tiếp tục đưa danh tiếng quả bom gợi cảm của Hollywood – Scarlett Johansson lan rộng toàn cầu.\r\n', '133');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'THE MEDIUM - ÂM HỒN NHẬP XÁC', N'NORTHERN CROSS', N'Thái Lan', N'Sawanee Utoomma, Narilya Gulmongkolpech', N'Banjong Pisanthanakun', N'Kinh Dị', '2021-11-19', N'Câu chuyện về gia đình một bà đồng, có khả năng kết nối với những âm hồn của thế giới bên kia luôn là đề tài gây nhiều hứng thú. Liệu sẽ ra sao nếu có sự xuất hiện của một linh hồn quỷ dữ đe dọa tính mạng của cả gia tộc? ', '120');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'VÙNG ĐẤT CÂM LẶNG 2', N'Paramount Pictures', N'Mỹ', N'Emily Blunt, Cillian Murphy, Noah Jupe, Millicent Simmonds', N'John Krasinski', N'Kinh Dị', '2021-12-10', N'A Quiet Place 2 là bộ phim kinh dị được mong chờ nhất 2020. Mất đi người chồng người cha trụ cột, mẹ góa con côi nhà Abbott sẽ ra sao ở thế giới đầy bọn quái vật? Chắc chắn mẹ con Evelyn Abbott sẽ phải trải qua rất nhiều nguy hiểm để tìm cách sống còn. Liệu biến cố gì sẽ xảy ra ở phần 2? \r\nNgoài nữ minh tinh Emily Blunt, Vùng Đất Câm Lặng 2 còn bổ sung ngôi sao thực lực Cillian Murphy vào dàn cast. \r\nPhim mới A Quiet Place 2 khởi chiếu tại các rạp chiếu phim toàn quốc 12.2021.', '97');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'DUNE: HÀNH TINH CÁT', N'Warner Bros', N'Mỹ', N'Timothée Chalamet, Zendaya, Rebecca Ferguson, Jason Momoa, Oscar Isaac', N'Denis Villeneuve', N'Hành Động, Phiêu Lưu, Tâm Lý', '2021-12-10', N'Dune lấy bối cảnh tương lai tại hành tinh hoang mạc Arrakis, nơi duy nhất sở hữu loại nhiên liệu quý giá Spice (Hương dược). Không chỉ giúp con người sống lâu hơn, Spice còn có sức mạnh siêu nhiên về khả năng suy nghĩ cũng như giúp di chuyển nhanh hơn cả vận tốc ánh sáng. Để quản lý nhiên liệu quý giá này, Công tước Leto đã đưa vợ mình là Lệnh bà Jessica cùng cậu con trai, người thừa kế của gia tộc Atreides là Paul đến vùng đất này. Tuy nhiên hàng loạt biến cố xảy ra, buộc Paul phải vượt qua nỗi sợ hãi của bản thân để làm chủ định mệnh của mình. \r\nPhim được cầm trịch bởi đạo diễn từng được đề cử giải Oscar Denis Villeneuve. Quy tụ dàn sao đình đám với Timothée Chalamet, Oscar Isaac, Rebecca Ferguson, Jason Momoa và Zendaya, Dune là tác phẩm điện ảnh không thể bỏ qua trong năm nay. \r\nPhim mới Dune dự kiến ra mắt tại các rạp chiếu phim 12.2021.', '156');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'VENOM: ĐỐI MẶT TỬ THÙ', N'Sony Pictures', N'Mỹ', N'Tom Hardy, Woody Harrelson, Michelle Williams', N'Andy Serkis', N'Hành Động', '2021-12-08', N'Venom: Let There Be Carnage tiếp tục câu chuyện vừa hài hước vừa máu me về chàng phóng viên Eddie Brock và bạn đồng hành Venom. Cả hai sẽ học cách sống chung thế nào khi nhân loại và quái vật ngoài hành tinh khác nhau quá đỗi? Thêm vào đó, sự xuất hiện của tên sát nhân hàng loạt Cletus / Carnage càng khiến cuộc sống yên bình quá xa với hai gã “loser”. \r\nTom Hardy tiếp tục hóa thân vào Eddie Brock / Venom – một trong những nhân vật phức tạp nhất nhà Marvel. \r\nPhim mới Venom: Đối Mặt Tử Thù dự kiến ra mắt tại các rạp chiếu phim 12.2021.', '97');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'THỤ HẢI: RỪNG TỬ KHÍ', N'Asmik Ace', N'Nhật Bản', N'Adachi Yumi, Hideko Hara', N'Takashi Shimizu', N'Kinh Dị', '2021-12-03', N'Tại khu rừng tự sát Aokigahara có một chiếc hộp bí ẩn phát ra những lời nguyền chết người, gây nên nhiều vụ án kinh hoàng. Liệu nguyên nhân là do đâu? \r\nPhim mới Thụ Hải: Rừng Tử Khí, ra mắt tại rạp chiếu phim từ 03.12.2021.', '116');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'PETER RABBIT 2: THE RUNAWAY', 'Columbia Pictures', N'Mỹ', N'Rose Byrne, Domhnall Gleeson, James Corden', N'Will Gluck', N'Hoạt Hình, Phiêu Lưu, Hài', '2021-12-31', N'Thomas và Bea đã kết hôn. Họ sống hạnh phúc và bình yên bên cạnh Peter và gia đình chú thỏ. Tuy nhiên, chán cuộc sống quá tĩnh lặng ở miền quê, Peter quyết định lên thành phố. Tại đây, chú gặp vô vàn rắc rối! \r\nPhim mới Peter Rabbit 2: The Runaway sớm ra mắt tại các rạp chiếu phim.', '93');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'VỆ SĨ SÁT THỦ 2: NHÀ CÓ NÓC', 'Millennium Flims', N'Mỹ', N'Samuel L. Jackson, Salma Hayek, Morgan Freeman, Ryan Reynolds ', N'Patrick Hughes', N'Hành Động', '2021-11-26', N'Chuyên viên an ninh cao cấp Michael Bryce quyết định bỏ việc vệ sĩ để nghỉ xả hơi. Ăn chơi chưa được bao lâu, anh lại phải làm bạn thân cùng sát thủ khét tiếng Darius Kincaid trong phi vụ tréo ngoe: cứu lấy \"nóc nhà\" của gã. Số phận không cho phép Michael lựa chọn. Lần này, không những mạng sống của cặp đôi nhà Kincaid \"ngàn cân treo sợi tóc\" mà cả châu u cũng rơi vào cảnh hiểm nguy. \r\nPhim mới Vệ Sĩ Sát Thủ 2: Nhà Có Nóc dự kiến khởi chiếu tại các rạp chiếu phim 19.11.2021.', '118');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'ĐIỆP VỤ CẢM TỬ', N'Flims', N'Mỹ ', N'Margot Robbie, Idris Elba, John Cena', N'James Gunn', N'Hành Động', '2021-12-19', N'The Suicide Squad - Điệp Vụ Cảm Tử kể về nhóm Task Force X bao gồm các thành viên là những phần tử nguy hiểm và có siêu năng lực đặc biệt được chỉ huy bởi Amanda Waller, họ có nhiệm vụ đột kích lên 1 hòn đảo có tên là Corto Maltese, nơi diễn ra cuộc đảo chính và thành lập chính phủ chống Mỹ. Tại hòn đảo này, các nhà chức trách đang kiểm soát một con quái vật tên là Starro - có năng lực biến con người thành cái xác không hồn, điều này khiến cho an ninh thế giới bị đe dọa một cách nghiêm trọng. Nhóm bọn Task Force X buộc phải đối mặt với vô số kẻ thù trên hòn đảo, nếu xảy ra bất cứ sai lầm bọn họ sẽ phải trả giá bằng mạng sống.', '132');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'SEANCE - CẦU HỒN', N'RLJE Films', N'Mỹ', N'Suki Waterhouse, Madisen Beaty, Inanna Sarkis, Ella-Rae Smith', N'Simon Barret', N'Kinh dị ', N'2021-11-26', N'Tại một trường nội trú danh tiếng dành cho nữ sinh, một nhóm bạn quyết định chơi trò chơi gọi hồn một cựu học sinh đã mất. Tuy nhiên, sau buổi cầu hồn, một nữ sinh trong nhóm là Kerrie đã chết một cách bí ẩn. Nữ sinh mới Camille Meadows (Suki Waterhouse) nhập học ngôi trường này và được phân vào phòng ký túc xá ngày trước của nữ sinh xấu số. Sau đó, Camille cảm thấy những sự việc kì quái xảy ra bên trong ngôi trường, và dần phát hiện được bí mật về cái chết của Kerrie. Tuy nhiên, sau khi Camille quyết định tìm kiếm sự thật, nhóm nữ sinh từng tham gia buổi cầu hồn năm xưa lần lượt mất tích một cách bí ẩn. Liệu có thế lực ma quái nào gây nên những sự việc khủng khiếp này?', '88');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'BỐ GIÀ', N'Trấn Thành Town, HKFilm và Galaxy Studio phối hợp sản xuất', N'Việt Nam', N'Trấn Thành, Tuấn Trần , Ngân Chi', N'Vũ Ngọc Đãng', N'Hài, Gia Đình', '2021-03-05', N'Sau thành công của web-drama, Trấn Thành đã thừa thắng xông lên, hợp tác với đạo diễn Vũ Ngọc Đãng, biên kịch Nhi Bùi để thực hiện phiên bản điện ảnh của Bố Già. Cùng với Trấn Thành, các nhân vật còn lại vẫn tiếp tục được đảm nhiệm bởi các gương mặt đã từng xuất hiện trong phiên bản đầu tiên là NSND Ngọc Giàu, Tuấn Trần, Lê Giang… \r\nRa mắt từ đầu năm 2020, đến thời điểm này, trung bình mỗi tập phim của Bố Già đều đạt trên 20 triệu lượt xem (cao nhất là tập 1 với 33 triệu lượt xem). \r\nTrong phim, Trấn Thành vào vai ông Tư – một tài xế xe ôm quần quật làm việc qua ngày để chăm lo cho gia đình của mình. Mặc dù khá bảo thủ, nóng nảy, thường xuyên quát tháo nhưng thực chất ông Tư lại là một người rất giàu lòng yêu thương – không chỉ với người thân mà còn có hàng xóm, bạn bè xung quanh và thậm chí là cả những người xa lạ. \r\nĐánh giá về thành công của Bố Già, bên cạnh diễn xuất hiệu quả của dàn diễn viên, điểm cộng của phim còn được quyết định bởi nội dung gần gũi, vừa cảm động mà cũng không thiếu những tình huống hài hước. Tuy vậy, đến cuối cùng, cái kết của tác phẩm lại gây ra tranh cãi vì nhiều khán giả cho rằng nó chưa thực sự hợp lý và còn thiếu cao trào. Liệu Bố Già bản điện ảnh có khắc phục được điều này?', '128');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'STAND BY ME DORAEMON', N'Shin-Ei Animation', N'Nhật Bản', N'Mizuta Wasabi, Megumi Oohara', N'Yamazaki Takashi', N'Hoạt Hình', '2021-12-17', N'Dựa trên tác phẩm lừng danh của ngài Fujiko F. Fujio, Stand By Me Doraemon 2 lồng ghép hai câu chuyện cảm động về bà nội quá cố và ngày kết hôn của Nobita. Liệu cậu nhóc hậu đậu và chậm chạp này có thể mang lại hạnh phúc cho người khác? \r\nPhim mới Stand By Me Doraemon 2 dự kiến ra mắt tại các rạp chiếu phim từ 17.12.2021. ', '100');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'LẬT MẶT: 48H', N'Ly Hai Production', N'Việt Nam', N'Ốc Thanh Vân, Huỳnh Đông, Mạc Văn Khoa, Võ Thành Tâm', N'Lý Hải', N'Hành Động', '2021-04-14', N'Một gia đình bị truy đuổi giữa vùng sông nước. Cơ hội nào cho người đàn ông cứu lấy vợ con khỏi bọn xã hội đen máu mặt? \r\nTrong phần 5 này, đạo diễn Lý Hải đã “mạnh tay” mời đạo diễn Kim Jung Min từ Hàn Quốc sang Việt Nam làm cố vấn hành động cho đoàn phim. Được biết, Kim Jung Min cũng chính là đạo diễn hành động của phim hay ra mắt năm 2018 The Witch: Part 1. The Subversion. Theo nhận xét của giới chuyên môn, yếu tố hành động trong siêu phẩm này được đánh giá cao bởi sự độc đáo, mạnh mẽ và ác liệt. Và với sự thể hiện này, tại giải thưởng điện ảnh danh giá Rồng Xanh lần thứ 39, Kim Jung Min và Park Jung Ryul đã nhận được đề cử ở hạng mục Kỹ thuật cho phần chỉ đạo hành động xuất sắc nhất. \r\nLật Mặt: 48H có sự tham gia của Võ Thành Tâm, Huỳnh Đông, Ốc Thanh Vân và Mạc Văn Khoa.', '110');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'THIÊN THẦN HỘ MỆNH', N'Lotte Entertainment', N'Việt Nam', N'Trúc Anh, Amee, Salim, Samuel An', 'Victor Vũ', N'Ly Kì', '2021-04-30', N'Cái chết bí ẩn của một ngôi sao trong giới giải trí, được đồn đoán rằng có liên quan đến loại búp bê ma thuật có tính chất bùa ngải hắc ám. Liệu bí ẩn khủng khiếp nào đang bị che giấu? \r\nHội tụ dàn hot girl tài năng như Trúc Anh, Salim, Amee, Samuel An và Chi Pu. Đạo diễn Victor Vũ lại cho ra mắt một bộ phim nói về cuộc sống trong giới showbiz, sự hào nhoáng và những góc khuất ẩn sau vẻ ngoài rực rỡ của thế giới nghệ thuật. \r\nMai Ly là một ngôi sao đang lên trong làng giải trí, đột nhiên người ta phát hiện cô đã chết sau khi rơi từ tầng thượng của một tòa nhà. Hàng loạt tin đồn được dấy lên, nhiều người cho rằng sự ra đi của Mai Ly có liên quan đến một loại ma thuật bùa ngải, hiện đang trú ngụ trong hình hài con búp bê hắc ám. \r\nPhim mới Thiên Thần Hộ Mệnh khởi chiếu tại các rạp chiếu phim từ 30.04.2021.', '124');
INSERT INTO `PHIM` (`phim_id`, `created_by`, `ten_phim`, `nha_san_xuat`, `quoc_gia`, `dien_vien`, `dao_dien`, `the_loai`, `ngay_phat_hanh`, `mo_ta`, `thoi_luong`) VALUES (NULL, '1', N'NGƯỜI NHỆN: KHÔNG CÒN NHÀ', N'Sony Pictures', N'Mỹ', N'Tom Holland, Zendaya, Willem Dafoe, Jamie Foxx, Benedict Cumberbatch', N'Jon Watts', N'Hành Động', '2021-12-17', N'Bị lộ mặt và trở thành kẻ thù quốc dân, Peter Parker tìm đến Dr Strange để nhờ thực hiện câu thần chú, khiến mọi người quên đi việc cậu là Spider-Man. \r\nThế nhưng, quá trình thực hiện xảy ra sự cố. Đa vũ trụ hình thành. Những kẻ thù ở các vũ trụ trước đây của Người Nhện lần lượt xuất hiện. Phải chống lại Green Goblin, Doc Ock, Electro, Sandman và Lizard…, làm thế nào Nhện nhí có thể bảo vệ được người thân và bạn bè? \r\nSpider-Man: No Way Home quy tụ dàn diễn viên khủng: Tom Holland, Benedict Cumberbatch, Willem Dafoe, Zendaya, J.K.Simmons, Jamie Foxx… \r\nPhim mới Spider-Man: No Way Home dự kiến ra rạp chiếu phim vào 12.2021.', '100');

-- INSERT IMAGES
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/eternals.jpg', '1', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/eternals.jpg', '1', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/shang-chi.jpg', '2', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/shang-chi.jpg', '2', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/black-widow.jpg', '3', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/black-widow.jpg', '3', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/poster-the-medium.jpg', '4', '0', '0');
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/poster-the-medium.jpg', '4', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/a-quiet-place-2.jpg', '5', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/a-quiet-place-2.jpg', '5', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/dune.jpg', '6', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/dune.jpg', '6', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/venom.jpg', '7', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/venom.jpg', '7', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/thu-hai.jpg', '8', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/thu-hai.jpg', '8', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/tho-peter-2.jpg', '9', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/the-peter-2.jfif', '9', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/ve-si-sat-thu.jpg', '10', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/ve-si-sat-thu.jpg', '10', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/the-suicide-squad.jpg', '11', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/the-suicide-squad.jpg', '11', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/sean.jfif', '12', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/sean.jpg', '12', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/bo-gia.jpg', '13', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/bo-gia.jpg', '13', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/doraemon.jpg', '14', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/doraemon.png', '14', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/lat-mat.jpg', '15', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/lat-mat.jpg', '15', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/thien-than-ho-menh.jpg', '16', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/thien-than-ho-menh.jpg', '16', '1', '1'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-details/spider-man.jpg', '17', '0', '0'); 
INSERT INTO `IMAGES` (`image_id`, `image_content`, `phim_id`, `status`, `the_loai`) VALUES (NULL, N'/images/phim-poster/spider-man.jpg', '17', '1', '1');

-- INSERT PHONG_CHIEU
INSERT INTO `PHONG_CHIEU`(`ten_phong`) VALUES (N'Phòng chiếu 1');
INSERT INTO `PHONG_CHIEU`(`ten_phong`) VALUES (N'Phòng chiếu 2');
INSERT INTO `PHONG_CHIEU`(`ten_phong`) VALUES (N'Phòng chiếu 3');
INSERT INTO `PHONG_CHIEU`(`ten_phong`) VALUES (N'Phòng chiếu 4');
INSERT INTO `PHONG_CHIEU`(`ten_phong`) VALUES (N'Phòng chiếu 5');

-- INSERT GHE
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('1','A01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('1','A02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('1','B01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('1','B02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('2','A01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('2','A02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('2','B01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('2','B02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('3','A01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('3','A02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('3','B01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('3','B02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('4','A01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('4','A02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('4','B01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('4','B02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('5','A01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('5','A02');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('5','B01');
INSERT INTO `GHE`(`phong_chieu_id`, `ma_ghe`) VALUES ('5','B02');

-- INSERT LICH_CHIEU
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','1','1','2022-02-01 15:00:00','2022-02-01 17:00:00', '50000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','2','2','2022-02-01 15:00:00','2022-02-01 17:00:00', '60000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','2','2','2022-01-03 16:00:00','2022-01-03 18:00:00', '60000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','3','3','2022-02-01 15:00:00','2022-02-01 17:00:00', '70000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','4','4','2022-01-01 15:00:00','2022-01-01 17:00:00', '80000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','1','2','2022-01-11 15:00:00','2022-01-11 17:00:00', '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','2','3','2022-01-12 15:00:00','2022-01-12 17:00:00', '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','3','4','2022-01-13 15:00:00','2022-01-13 17:00:00', '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','4','1','2022-01-14 15:00:00','2022-01-14 17:00:00', '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','1','3','2022-01-16 15:00:00','2022-01-16 17:00:00', '90000');
---- Init current date data
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',NOW(),DATE_ADD(NOW(), INTERVAL 2 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','4','16',NOW(),DATE_ADD(NOW(), INTERVAL 2 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','3','15',NOW(),DATE_ADD(NOW(), INTERVAL 2 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',DATE_ADD(NOW(), INTERVAL 3 HOUR),DATE_ADD(NOW(), INTERVAL 5 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',DATE_ADD(NOW(), INTERVAL 6 HOUR),DATE_ADD(NOW(), INTERVAL 8 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',DATE_ADD(NOW(), INTERVAL 1 DAY),DATE_ADD(NOW(), INTERVAL 2 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 2 HOUR),DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 4 HOUR), '90000');
INSERT INTO `LICH_CHIEU`(`created_by`, `phong_chieu_id`, `phim_id`, `gio_bat_dau`, `gio_ket_thuc`, `gia`) VALUES ('1','5','17',DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 5 HOUR),DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 7 HOUR), '90000');

-- INSERT INTO VE_PHIM
INSERT INTO `VE_PHIM`(`ghe_id`, `lich_chieu_id`, `created_by`, `owner`) VALUES ('1','1','1','3');